import React, { Component } from 'react'

import Card from '../card/Card';

import crowd from '../../images/crowd1.jpeg';
import history from '../../images/history2.jpg';
import geography from '../../images/geography2.jpg';
import economy from '../../images/sua-economy1.jpg';
import c from '../../images/c1.png';
import art from '../../images/art1.jpg';

export default class Cards extends Component {
    render() {
        const items = [
            { title: 'istorie', image: history, text: 'Regiunea era locuită de cca. 6.000 nativi americani lenapi, în momentul descoperirii sale în 1524, de către Giovanni de Verrazzano, un explorator italian, în seviciul coroanei franceze, care a denumit-o „Nouvelle Angoulême“ (Noul Angoulême). Instalarea europeană a început odată cu fondarea unei așezări olandeze în 1614 ce se ocupa cu comerțul de blănuri, denumită mai târziu „Noul Amsterdam“, situată în sudul Manhattanului. Directorul-general colonial, olandezul Peter Minuit, a cumpărat insula Manhattan mai târziu în 1626, oferind în schimb 60 guilderi (denumirea monedelor de aur olandeze). Legenda, acum recunoscuta ca fiind falsă, susținea că Minuit ar fi cumpărat zona cu mărgele din sticlă valorând 24$. În 1664, orașul a fost cucerit de către englezi și redenumit New York, după Ducele englez de York și Albany. La sfârșitul celui de-al Doilea Război Anglo-Olandez, Olanda a căpătat controlul asupra insulei Run (care la acea vreme avea o mai mare importanță), în schimb Anglia obținând New York-ul. Până în anul 1700, populația lenapilor a scăzut la 200.' },
            { title: 'populatie', image: crowd, text: ' New York-ul este cel mai populat oraș din Statele Unite, în 2007 populația sa estimată fiind de 8.274.527 (în 1990 acesta fiind de 7,3 milioane). Aceasta reprezintă aproximativ 40% din populația totală a statului New York, și un procent similar din totalul populației metropolitane. În ultimul deceniu, populația orașului a crescut, demografii estimând că populația New York-ului va ajunge la 9,2 - 9,5 milioane până în 2030. Două dintre caracteristicile demografice importante ale orașului sunt densitatea și diversitatea culturală. Densitatea New York-ului este de 10.194 loc./km², fiind astfel municipalitatea cu peste 100.000 locuitori și cu cea mai mare densitate din Statele Unite.[23] În Manhattan densitatea ajunge la 25.846 loc./km², cea mai mare din oricare stat din S.U.A. New York-ul are o diversitate covârșitoare. De-a lungul istoriei sale, orașul a fost un punct de stabilire al imigranților. Astăzi, 36% din populația sa este născută în altă țară.' },
            { title: 'economie',image: economy, text: `New York-ul este un centru comercial și financiar mondial, centru de comunicații, al modei, artei și divertismentului. Multe dintre ramurile economice americane importante, cât și televiziunea și transmisiile radio americane, își au sediile la New York. Tot aici se află și sediul Națiunilor Unite. Majoritatea băncilor, a firmelor de brokeraj și a burselor – bursele New York și American, bursele de mărfuri și cele maritime – sunt situate în zona Wall Street, primul centru financiar al lumii, sprijinit pe economia cea mai puternică, mai precis singura capabilă să absoarbă enormele excedente financiare ale Japoniei.

              Trebuie menționat și faptul că șase dintre primele opt intreprinderi din Statele Unite își au sediul în regiunea new-yorkeză și că șase din primele opt bănci sunt conduse din Manhattan. Orașul este totodată și cel mai are centru comercial en-gros din SUA: printre cele mai importante produse comercializate se numără cerealele, blănurile, hârtia, carnea și pieile. Comerțul en-detail din New York este focalizat în centrul Manhattan-ului. În Bronx și Brooklyn sunt de asemenea zone importante destinate comerțului en-gros și en-detail. Pentru a deservi aceste afaceri și comerțul, orașul are sute de agenții de publicitate, multe dintre acestea fiind situate pe sau în jurul bulevardului Madison Avenue.` },
            { title: 'arhitectura', image: art, text: `Tipul de clădiri cel mai frecvent asociate cu New York-ul sunt zgârie-norii. În New York se găsesc în jur de 4493 zgârie-nori, mai mult decât în orice alt oraș din lume. Fiind înconjurat aproape în întregime de apă, densitatea sa mare, și capacitățile comerciale ale orașului în diferitele sale zone au dus la apariția celui mai mare număr de clădiri de birouri și blocuri de apartamente din lume.

            Clădirile din New York prezintă numeroase stiluri arhitecturale importante. Printre acestea se află și Woolworth Building (1913), un zgârie-nori în stil neogotic ce prezintă numeroase detalii la scară mare, caracteristice acestui stil, ce pot fi observate de la câteva sute de metri distanță. În 1916 a fost adoptată Reforma Zoning ce limita construcția zgârie-norilor la un anumit procent pe o zonă definită, pentru a permite luminii soarelui să ajungă până la nivelul de jos. Construcția în stil Art Deco a Chrysler Building (1930) cu al său vârf conic și cupolă din oțel este una dintre clădirile ce respecta prevederile propuse de Reforma Zoning. Clădirea este considerată de către mulți istorici ca fiind cea mai măreață clădire a New York-ului, cu ornamentațiile sale distinctive.Un exemplu extrem de important al stilului internațional în Statele Unite este Seagram Building (1957), ieșind în evidență datorită fațadei sale ale cărei grinzi de culoare bronz sunt lăsate la vedere. Condé Nast Building (2000) este un exemplu de zgârie-nori construiți în stilul verde, sau stilul eco din America.` },
            { title: 'geografie',image: geography, text: 'Orașul New York este situat în nord-estul Statelor Unite ale Americii, și în sud-estul Statului New York, la aproximativ jumătatea distanței dintre Washington D.C. și Boston. Zona de la gura râului Hudson, ce se varsă în Oceanul Atlantic, a ajutat orașul să crească în importanță din punct de vedere al comerțului. O mare parte a New York-ului este construită pe cele trei insule ale Manhattanului, Staten Island și Long Island, astfel suprafața sa fiind dispersată, ajutând la creșterea densității. Orașul se întinde pe uscat pe o suprafață de 831,4 km². Cel mai înalt punct din oraș este Todt Hill din Staten Island, ce se află la 124,9 m deasupra nivelului mării, care este de asemenea și cel mai înalt punct al coastei de est, sud de Maine. ' },
            { title: 'educatia', image: c,text: `Sistemul public de învățământ al orașului este cel mai mare din America. În jur de 1,1 milioane de elevi învață în peste 1.200 de școli diferite. Există aproximativ 900 de școli private, unele dintre ele fiind printre cele mai prestigioase din S.U.A. Deși nu este văzut în mod special ca fiind un oraș axat pe învățământ, în New York se găsesc aproximativ 594.000 de studenți, mai mult decât în orice alt oraș din Statele Unite. În 2005, trei din cinci locuitori ai Manhattan-ului erau absolvenți de facultate, iar unul din patru avea pregătire de specialitate, formând astfel unul dintre cele mai mari numere de rezidenți cu studii superioare din orice oraș american.

            Biblioteca Publică din New York, având cel mai mare sistem de biblioteci publice din țară, servește Manhattanul, The Bronx și Staten Island. Queens este servit de către Librăria Publică "Queens Borough", aceasta fiind al doilea sistem de biblioteci publice ca mărime, iar Biblioteca Publică din Brooklyn servește Brooklyn-ul.Biblioteca Publică din New York are, de asemenea, câteva biblioteci de cercetare, printre care și "Arthur Schomburg" Center for Research in Black Culture .` },
        ];
        return (
            <div>
                { items && items.map((item) => <Card item={item} /> ) }
                
            </div>
        )
    }
}
